version: '3.8'

services:
  frontend:
    build:
      context: ../..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - HALF_TIME_API_URL=http://localhost:8000